# Execrcices numpy
- importer numpy
- crée un taleau 3x3 de zeros, de 1 , ...
- crée un tableau des nb de 1 à 1000
- afficher les 10 premier et les 10 derniers
- en afficher un sur 33

In [13]:
import numpy as np
t= np.zeros((3,3))
t, t+1, (t+1+np.identity(3))**4

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[16.,  1.,  1.],
        [ 1., 16.,  1.],
        [ 1.,  1., 16.]]))

In [19]:
n1000=np.arange(1000)
n1000[:10],n1000[-10:],n1000[::33],

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([990, 991, 992, 993, 994, 995, 996, 997, 998, 999]),
 array([  0,  33,  66,  99, 132, 165, 198, 231, 264, 297, 330, 363, 396,
        429, 462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825,
        858, 891, 924, 957, 990]))

# Tracé de graphique
- importer maplotlib
-


In [20]:
%matplotlib inline
im

In [22]:
plot(3)

NameError: name 'plot' is not defined